a = input('Digite algo:')
print('Tipo: {}'.format(type(a)))
print('É alpha? {}'.format(a.isalpha()))
print('É numérico? {}'.format(a.isnumeric()))
print('Tudo maiusculo? {}'.format(a.isupper()))
print('Tudo minusculo? {}'.format(a.islower()))
print('É titulo? {}'.format(a.istitle()))
print('É espaço? {}'.format(a.isspace()))
print('É printavél? {}'.format(a.isprintable()))
print('É identificavél? {}'.format(a.isidentifier()))
print('É decimal? {}'.format(a.isdecimal()))
print('É digito? {}'.format(a.isdigit()))
print('É ASCII? {}'.format(a.isascii()))
print('É alphanumérico? {}'.format(a.isalnum()))